source 'http://rubygems.org'

gem 'rails', '3.1.3'

# Deploy with Capistrano
# gem 'capistrano'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'therubyracer'
end

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
group :development, :test do
	gem 'ruby-debug19'
	gem 'hpricot'
	gem 'ruby_parser'
end

# not actually running any tests for Jingle Jaws.  Feel free to remove this group.
group :test do
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'rspec-rails'
  gem 'factory_girl_rails', :require => false
  gem 'pickle'
  gem 'rb-inotify'
  gem 'libnotify'
  gem 'spork'
  gem 'guard'
  gem 'guard-spork'
  gem 'launchy'

  # Pretty printed test output
  gem 'turn', :require => false
end

# Bundle the extra gems:
#gem 'mongrel', '>= 1.2.0.pre2'
gem 'unicorn'

gem 'haml'

gem 'closure-sprockets', :git=>'git://github.com/igrigorik/closure-sprockets.git'
gem 'closure-compiler'

gem 'jquery-rails'
